# Development only docker-compose file
# Production version will be placed in docker-compose-prod.yml

version: '3.7'

networks:
  app:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
    web:
        build: .
        command: flask run -h 0.0.0.0
        ports:
          - 5000:5000
        env_file:
          - .env
        networks:
          app:
              ipv4_address: 172.20.0.6
        restart: always
        volumes:
          - .:/code/
        depends_on:
          - db
    db:
        image: postgres:12
        env_file:
          - .env-postgres
        networks:
          app:
              ipv4_address: 172.20.0.5
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
